# GitHub <https://github.com/rust-lang/rustfmt/blob/master/README.md#license>
# Configurator <https://rust-lang.github.io/rustfmt/?version=master>

unstable_features            = true
edition                      = "2018"

brace_style                  = "SameLineWhere"
control_brace_style          = "AlwaysSameLine"
imports_layout               = "HorizontalVertical"
indent_style                 = "Block"
imports_granularity          = "Crate"
newline_style                = "Auto"
hex_literal_case             = "Upper"
binop_separator              = "Front"

hard_tabs                    = true
format_code_in_doc_comments  = false
combine_control_expr         = false
reorder_imports              = false
reorder_modules              = false

condense_wildcard_suffixes   = true
error_on_line_overflow       = true
error_on_unformatted         = true
fn_single_line               = true
format_macro_bodies          = true
format_macro_matchers        = true
format_strings               = true
match_block_trailing_comma   = true
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
use_field_init_shorthand     = true
wrap_comments                = true

blank_lines_lower_bound      = 0
blank_lines_upper_bound      = 1
tab_spaces                   = 4
enum_discrim_align_threshold = 45
struct_field_align_threshold = 45
inline_attribute_width       = 70
comment_width                = 90
max_width                    = 110
