[package]
name = "apic_example"
edition = "2021"
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bootloader_api = { workspace = true }
x86_64 = "=0.15.1"
lazy_static = "=1.5.0"
spin = "=0.9.8"
acpi = "=4.1.1"
log = "=0.4.19"
